/**
 * Smart Home Planner — PDF Export
 *
 * Pages generated:
 *   1. Cover          — logo, app name, house name, date, key stats
 *   2+  Summary       — full dashboard stats: status, connectivity, integrations,
 *                       brand, type, local/UPS, power, battery, labels,
 *                       battery-change alerts, pending/not-working/wishlist lists
 *   n+  Device table  — complete inventory with status colour-coding
 *   n+  Connections   — port/network connection list (if any)
 *   n+  Diagram       — background image + device nodes + labelled connections
 *
 * CDN dependencies (load in HTML before this file):
 *   jsPDF 2.5.1         https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js
 *   jspdf-autotable 3.8 https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.8.2/jspdf.plugin.autotable.min.js
 *
 * Globals from common.js (loaded before this file):
 *   loadData(), loadSettings(), getUiPreference(), loadMapPositions(),
 *   loadMapImagePositions(), buildAppUrl(), formatConnectivity(),
 *   formatDeviceType(), getFriendlyOption(), showToast()
 */

'use strict';

// ─── Layout constants ──────────────────────────────────────────────────────────
const _PDF_W        = 210;
const _PDF_H        = 297;
const _PDF_MARGIN   = 14;
const _PDF_CW       = _PDF_W - _PDF_MARGIN * 2;   // 182 mm usable width
const _PDF_HEADER_H = 22;                           // top zone reserved per content page
const _PDF_BOTTOM_MARGIN = 20;
const _PDF_FOOTER_Y = _PDF_H - 10;
const _FOOTER_TEXT  = 'Generated by Smart Home Planner - planner.smarthomecompared.com';

// ─── Colour palette [R, G, B] ─────────────────────────────────────────────────
const _C = {
    coverBg:      [ 6,  18,  39],
    coverBgSoft:  [13,  31,  58],
    coverGlowA:   [14, 116, 144],
    coverGlowB:   [29,  78, 216],
    coverPanel:   [13,  28,  51],
    coverCard:    [19,  41,  75],
    coverStroke:  [71,  94, 128],
    headerBg:     [30,  41,  59],
    pageBg:       [247, 249, 252],
    pageHeaderBg: [255, 255, 255],
    pageHeaderTint:[226, 232, 240],
    pageBorder:   [203, 213, 225],
    cardBg:       [255, 255, 255],
    cardMutedBg:  [241, 245, 249],
    cardBorder:   [226, 232, 240],
    accent:       [14, 116, 144],
    accentDark:   [15,  83,  95],
    accentSoft:   [204, 251, 241],
    tableHead:    [30,  41,  59],
    tableGrid:    [226, 232, 240],
    rowAlt:       [248, 250, 252],
    rowAlertBg:   [254, 242, 242],
    textLight:    [248, 250, 252],
    textMuted:    [148, 163, 184],
    textOnLight:  [ 71,  85, 105],
    textStrong:   [ 15,  23,  42],
    working:      [ 22, 163,  74],
    pending:      [234,  88,  12],
    notWorking:   [220,  38,  38],
    wishlist:     [124,  58, 237],
    connEthernet: [ 59, 130, 246],  // #3b82f6 — matches Cytoscape ethernet edge
    connUsb:      [ 20, 184, 166],  // #14b8a6 — matches Cytoscape usb edge (teal)
    connPower:    [245, 158,  11],  // #f59e0b — matches Cytoscape power edge (amber)
    connWifi:     [ 56, 189, 248],  // #38bdf8 — matches Cytoscape wifi edge (sky, dashed)
    connZigbee:   [250, 204,  21],  // #facc15 — matches Cytoscape zigbee edge (yellow, dashed)
    connZwave:    [ 34, 197,  94],  // #22c55e — matches Cytoscape z-wave edge (green, dashed)
    connDefault:  [100, 116, 139],
    barBg:        [226, 232, 240],
    barFill:      [ 14, 116, 144],
};

const _STATUS_LABELS = {
    'working':     'Working',
    'pending':     'Pending',
    'not-working': 'Not Working',
    'wishlist':    'Wishlist',
};

const _PORT_LABELS = {
    'ethernet-input':  'Ethernet In',
    'ethernet-output': 'Ethernet Out',
    'usb-input':       'USB In',
    'usb-output':      'USB Out',
    'power-input':     'Power In',
    'power-output':    'Power Out',
};

const _PORT_SHORT = {
    'ethernet': 'ETH',
    'usb':      'USB',
    'power':    'PWR',
};

function _drawPageCanvas(doc) {
    doc.setFillColor(..._C.pageBg);
    doc.rect(0, 0, _PDF_W, _PDF_H, 'F');
}

// ─── Main orchestrator ─────────────────────────────────────────────────────────

async function generateSmartHomePDF() {
    if (!window.jspdf || typeof window.jspdf.jsPDF !== 'function') {
        showToast('PDF library not loaded. Please refresh and try again.', 'error');
        return;
    }

    const btn    = document.getElementById('export-pdf-btn');
    const status = document.getElementById('export-pdf-status');

    if (btn)    btn.disabled = true;
    if (status) status.style.display = 'inline';

    try {
        const [data, haConfig, settings] = await Promise.all([
            loadData(),
            window.loadHaConfig().catch(() => ({})),
            loadSettings(),
        ]);

        const houseName = ((haConfig && haConfig.location_name) || '').trim() || 'My Smart Home';
        const now       = new Date();
        const dateStr   = now.toLocaleDateString(undefined, {
            year: 'numeric', month: 'long', day: 'numeric',
        });

        // Pre-load the app logo for the cover page
        const logoDataUrl = await _fetchDataUrl(buildAppUrl('img/logo.png')).catch(() => null);

        const config = {
            houseName,
            dateStr,
            settings,
            logoDataUrl,
            stats: {
                totalDevices: data.devices.length,
                totalAreas:   (data.areas  || []).length,
                totalFloors:  (data.floors || []).length,
                working:      data.devices.filter(d => d.status === 'working').length,
                pending:      data.devices.filter(d => d.status === 'pending').length,
                notWorking:   data.devices.filter(d => d.status === 'not-working').length,
            },
        };

        const { jsPDF } = window.jspdf;
        const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

        _pdfCoverPage(doc, config);

        // Reserve page 2 for the Table of Contents (filled in after all pages are rendered)
        doc.addPage();
        const TOC_PAGE = doc.getNumberOfPages(); // = 2
        const nextPg   = () => doc.getNumberOfPages() + 1;

        const tocPages = {};
        tocPages.visualSummary = nextPg();
        _pdfChartsPage(doc, data);

        tocPages.summary = nextPg();
        _pdfSummaryPage(doc, data, config);

        tocPages.deviceDetails = nextPg();
        _pdfDeviceDetailPages(doc, data, config);

        tocPages.diagram = nextPg();
        await _pdfDiagramPage(doc, data);

        tocPages.testCases = nextPg();
        _pdfTestCasesPages(doc, data);

        _pdfFooters(doc);

        // Now fill in the TOC on page 2
        doc.setPage(TOC_PAGE);
        _pdfTocPage(doc, tocPages, config);

        const yy = now.getFullYear();
        const mm = String(now.getMonth() + 1).padStart(2, '0');
        const dd = String(now.getDate()).padStart(2, '0');
        doc.save(`smart-home-inventory-${yy}-${mm}-${dd}.pdf`);

        showToast('PDF exported successfully.', 'success');

    } catch (err) {
        console.error('[pdf-export] Generation failed:', err);
        showToast('PDF export failed: ' + (err.message || String(err)), 'error');
    } finally {
        if (btn)    btn.disabled = false;
        if (status) status.style.display = 'none';
    }
}

// ─── Page 1: Cover ─────────────────────────────────────────────────────────────

function _pdfCoverPage(doc, { houseName, dateStr, stats, logoDataUrl }) {
    const W = _PDF_W;
    const H = _PDF_H;

    doc.setFillColor(..._C.coverBg);
    doc.rect(0, 0, W, H, 'F');

    doc.setFillColor(..._C.coverBgSoft);
    doc.rect(0, 0, W, 116, 'F');

    doc.setFillColor(..._C.coverGlowA);
    doc.circle(W - 6, 28, 42, 'F');
    doc.setFillColor(..._C.coverGlowB);
    doc.circle(18, H - 16, 50, 'F');

    const panelX = 10;
    const panelY = 10;
    const panelW = W - 20;
    const panelH = H - 20;

    doc.setFillColor(..._C.coverPanel);
    doc.roundedRect(panelX, panelY, panelW, panelH, 6, 6, 'F');
    doc.setDrawColor(..._C.coverStroke);
    doc.setLineWidth(0.45);
    doc.roundedRect(panelX, panelY, panelW, panelH, 6, 6, 'D');

    doc.setFillColor(..._C.accent);
    doc.roundedRect(panelX, panelY, panelW, 5, 3, 3, 'F');

    const logoSize = 20;
    const logoX = panelX + 12;
    const logoY = panelY + 11;
    if (logoDataUrl) {
        try {
            doc.addImage(logoDataUrl, 'PNG', logoX, logoY, logoSize, logoSize);
        } catch (_) {
            _drawLogoPlaceholder(doc, logoX + logoSize / 2, logoY + logoSize / 2, logoSize / 2);
        }
    } else {
        _drawLogoPlaceholder(doc, logoX + logoSize / 2, logoY + logoSize / 2, logoSize / 2);
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(..._C.textLight);
    doc.text('Smart Home Planner', logoX + logoSize + 6, logoY + 8);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(..._C.textMuted);
    doc.text('planner.smarthomecompared.com', logoX + logoSize + 6, logoY + 12.8);

    doc.setDrawColor(..._C.coverStroke);
    doc.setLineWidth(0.25);
    doc.line(panelX + 10, panelY + 40, panelX + panelW - 10, panelY + 40);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(31);
    doc.setTextColor(..._C.textLight);
    doc.text('Smart Home', panelX + 12, panelY + 62);
    doc.setTextColor(..._C.accentSoft);
    doc.text('Inventory Report', panelX + 12, panelY + 76);

    const coverHouseName = String(houseName || '').trim();
    const showCoverHouseName = coverHouseName.toLowerCase() !== 'home';
    const dateY = showCoverHouseName ? (panelY + 97) : (panelY + 92);

    if (showCoverHouseName && coverHouseName) {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(14);
        doc.setTextColor(..._C.textLight);
        doc.text(coverHouseName, panelX + 12, panelY + 90);
    }

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(..._C.textMuted);
    doc.text(dateStr, panelX + 12, dateY);

    if (stats) {
        const boxes = [
            { value: stats.totalDevices, label: 'DEVICES',     sub: `${stats.working} working` },
            { value: stats.totalAreas,   label: 'AREAS',       sub: ' '                        },
            { value: stats.totalFloors,  label: 'FLOORS',      sub: ' '                        },
        ];

        const boxW   = 49;
        const boxH   = 34;
        const gapX   = 5;
        const total  = boxes.length * boxW + (boxes.length - 1) * gapX;
        const startX = panelX + (panelW - total) / 2;
        const boxY   = panelY + 112;

        boxes.forEach((box, i) => {
            const bx = startX + i * (boxW + gapX);

            doc.setFillColor(..._C.coverCard);
            doc.roundedRect(bx, boxY, boxW, boxH, 4, 4, 'F');

            doc.setFillColor(..._C.accent);
            doc.roundedRect(bx, boxY, boxW, 3, 1.5, 1.5, 'F');

            doc.setDrawColor(..._C.coverStroke);
            doc.setLineWidth(0.2);
            doc.roundedRect(bx, boxY, boxW, boxH, 4, 4, 'D');

            doc.setFont('helvetica', 'bold');
            doc.setFontSize(23);
            doc.setTextColor(..._C.textLight);
            doc.text(String(box.value), bx + boxW / 2, boxY + 18.5, { align: 'center' });

            doc.setFont('helvetica', 'bold');
            doc.setFontSize(7);
            doc.setTextColor(..._C.textMuted);
            doc.text(box.label, bx + boxW / 2, boxY + 27, { align: 'center' });

            if (box.sub && box.sub.trim()) {
                doc.setFont('helvetica', 'normal');
                doc.setFontSize(6.5);
                doc.setTextColor(..._C.textMuted);
                doc.text(box.sub, bx + boxW / 2, boxY + 31.5, { align: 'center' });
            }
        });
    }

    if (stats) {
        const pills = [
            { label: 'Working',     count: stats.working,    color: _C.working },
            { label: 'Pending',     count: stats.pending,    color: _C.pending },
            { label: 'Not Working', count: stats.notWorking, color: _C.notWorking },
        ];

        const pillH   = 9;
        const pillGap = 5;
        const contentW = panelW - 24;
        const pillW   = (contentW - pillGap * (pills.length - 1)) / pills.length;
        const pillX0  = panelX + 12;
        const pillY   = panelY + 152;

        pills.forEach((pill, i) => {
            const px = pillX0 + i * (pillW + pillGap);

            doc.setFillColor(...pill.color);
            doc.roundedRect(px, pillY, pillW, pillH, 2.2, 2.2, 'F');

            doc.setFont('helvetica', 'bold');
            doc.setFontSize(7);
            doc.setTextColor(255, 255, 255);
            doc.text(`${pill.label}: ${pill.count}`, px + pillW / 2, pillY + pillH / 2, {
                align: 'center', baseline: 'middle',
            });
        });
    }

}

/** Draws a simple geometric placeholder when the logo image is unavailable. */
function _drawLogoPlaceholder(doc, cx, cy, r) {
    doc.setFillColor(..._C.accent);
    doc.circle(cx, cy, r, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(r * 1.8);
    doc.setTextColor(255, 255, 255);
    doc.text('SH', cx, cy + r * 0.35, { align: 'center' });
}

// ─── Summary pages (full dashboard stats) ─────────────────────────────────────

function _pdfSummaryPage(doc, data, { settings }) {
    doc.addPage();

    const { devices, areas, floors, labels } = data;
    const areaMap  = new Map((areas  || []).map(a => [a.id,  a]));
    const labelMap = new Map((labels || []).map(l => [l.id,  l]));

    // ── Shared autoTable base options ─────────────────────────────────────────
    const base = {
        theme:              'grid',
        styles:             {
            fontSize: 8.3,
            cellPadding: 2.1,
            overflow: 'linebreak',
            lineColor: _C.tableGrid,
            lineWidth: 0.12,
            textColor: _C.textOnLight,
        },
        headStyles:         {
            fillColor: _C.tableHead,
            textColor: _C.textLight,
            fontStyle: 'bold',
            fontSize: 8.2,
            lineColor: _C.tableHead,
            lineWidth: 0.12,
        },
        alternateRowStyles: { fillColor: _C.rowAlt },
        margin:             { top: _PDF_HEADER_H + 1, left: _PDF_MARGIN, right: _PDF_MARGIN, bottom: _PDF_BOTTOM_MARGIN },
        didDrawPage:        () => _drawPageHeader(doc, 'Summary'),
    };

    /**
     * Renders a titled breakdown table with Count and % columns.
     * Uses a colSpan heading row as the visual section title.
     * @param {string}   sectionTitle – appears in a full-width accent header row
     * @param {string[]} colHeaders   – e.g. ['Type', 'Devices', '%']
     * @param {Array[]}  rows         – raw rows [[label, count], …]
     * @param {number}   total        – denominator for % calculation
     * @param {number}   startY
     * @param {number}   [barCol]     – column index to render as a mini progress bar
     */
    const sectionTable = (sectionTitle, colHeaders, rows, total, startY, barCol) => {
        const ncols   = colHeaders.length;
        const pctRows = rows.map(([label, count, extra]) => {
            const pct = total > 0 ? Math.round((count / total) * 100) : 0;
            return ncols === 3 && extra === undefined
                ? [label, count, pct + '%']
                : [label, count, extra !== undefined ? extra : pct + '%'];
        });

        const opts = {
            ...base,
            startY,
            head: [
                [{ content: sectionTitle, colSpan: ncols, styles: {
                    fillColor: _C.accent, textColor: [255, 255, 255],
                    fontStyle: 'bold', fontSize: 9, halign: 'left',
                } }],
                colHeaders,
            ],
            body: pctRows,
            columnStyles: {
                0: { cellWidth: 'auto' },
                1: { cellWidth: 28, halign: 'right', fontStyle: 'bold' },
                ...(ncols >= 3 ? { 2: { cellWidth: 22, halign: 'right' } } : {}),
            },
        };

        // Optional mini-bar rendering in a dedicated last column
        if (barCol !== undefined) {
            opts.didDrawCell = function (d) {
                if (d.section !== 'body' || d.column.index !== barCol) return;
                const pct   = parseInt(d.row.raw[d.row.raw.length - 1]) || 0;
                const barW  = d.cell.width - 4;
                const barH  = 2.5;
                const barX  = d.cell.x + 2;
                const barY  = d.cell.y + (d.cell.height - barH) / 2;
                doc.setFillColor(..._C.barBg);
                doc.rect(barX, barY, barW, barH, 'F');
                doc.setFillColor(..._C.barFill);
                doc.rect(barX, barY, Math.max(0, (pct / 100) * barW), barH, 'F');
            };
        }

        doc.autoTable(opts);
    };

    let y = _PDF_HEADER_H + 1;

    // ══ Section 1: Device Status ══════════════════════════════════════════════
    const totalAll  = devices.length;
    const active    = devices.filter(d => d.status !== 'wishlist');

    doc.autoTable({
        ...base,
        startY: y,
        head: [
            [{ content: 'Device Overview', colSpan: 2, styles: {
                fillColor: _C.accent, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9,
            } }],
            ['Metric', 'Value'],
        ],
        body: [
            ['Total Devices',           totalAll],
            ['Active (non-wishlist)',    active.length],
            ['Areas',                   (areas  || []).length],
            ['Floors',                  (floors || []).length],
        ],
        columnStyles: {
            0: { cellWidth: 'auto' },
            1: { cellWidth: 28, halign: 'right', fontStyle: 'bold' },
        },
    });
    y = doc.lastAutoTable.finalY + 5;

    // ══ Section 2: Brand ══════════════════════════════════════════════════════
    const byBrand  = _groupBy(devices.filter(d => d.brand), d => d.brand);
    const brandTotal = devices.filter(d => d.brand).length;
    const brandRows  = Object.entries(byBrand)
        .sort((a, b) => b[1].length - a[1].length)
        .map(([k, v]) => {
            const lbl = (settings && settings.brands)
                ? (getFriendlyOption(settings.brands, k, formatDeviceType) || k) : k;
            return [lbl, v.length];
        });

    if (brandRows.length) {
        sectionTable('Devices by Brand', ['Brand', 'Devices', '%'], brandRows, brandTotal, y);
        y = doc.lastAutoTable.finalY + 5;
    }

    // ══ Section 5: Device Type ════════════════════════════════════════════════
    const byType   = _groupBy(devices.filter(d => d.type), d => d.type);
    const typeTotal = devices.filter(d => d.type).length;
    const typeRows  = Object.entries(byType)
        .sort((a, b) => b[1].length - a[1].length)
        .map(([k, v]) => {
            const lbl = (settings && settings.types)
                ? (getFriendlyOption(settings.types, k, formatDeviceType) || k)
                : _fmtType(k);
            return [lbl, v.length];
        });

    if (typeRows.length) {
        sectionTable('Devices by Type', ['Type', 'Devices', '%'], typeRows, typeTotal, y);
        y = doc.lastAutoTable.finalY + 5;
    }

    // ══ Section 6: Installed / Controlled Areas ═══════════════════════════════
    const _resolveAreaName = (areaId, fallbackLabel) => {
        const normalized = String(areaId || '').trim();
        if (!normalized) return fallbackLabel;
        const area = areaMap.get(normalized) || areaMap.get(areaId);
        return area ? area.name : normalized;
    };
    const _areaRows = (selector, emptyLabel) => {
        const counts = {};
        devices.forEach((device) => {
            const areaId = String(selector(device) || '').trim();
            const key = areaId || '__none__';
            counts[key] = (counts[key] || 0) + 1;
        });
        return Object.entries(counts)
            .sort((a, b) => b[1] - a[1])
            .map(([areaId, count]) => {
                if (areaId === '__none__') return [emptyLabel, count];
                return [_resolveAreaName(areaId, emptyLabel), count];
            });
    };

    const controlledAreaRows = _areaRows((device) => device.controlledArea, 'No Controlled Area');
    if (controlledAreaRows.length) {
        sectionTable('Devices by Controlled Area', ['Controlled Area', 'Devices', '%'], controlledAreaRows, totalAll, y);
        y = doc.lastAutoTable.finalY + 5;
    }

    const installedAreaRows = _areaRows((device) => device.area, 'No Installed Area');
    if (installedAreaRows.length) {
        sectionTable('Devices by Installed Area', ['Installed Area', 'Devices', '%'], installedAreaRows, totalAll, y);
        y = doc.lastAutoTable.finalY + 5;
    }

    // ══ Section 8: Battery ════════════════════════════════════════════════════
    const battDevices = devices.filter(d => d.power === 'battery' && d.batteryType);
    const byBattType  = _groupBy(battDevices, d => d.batteryType);
    const battRows    = Object.entries(byBattType)
        .sort((a, b) => b[1].length - a[1].length)
        .map(([type, devs]) => {
            const cells = devs.reduce((s, d) => s + (Number(d.batteryCount) || 1), 0);
            return [type, devs.length, cells, '-'];
        });

    if (battRows.length) {
        doc.autoTable({
            ...base,
            startY: y,
            head: [
                [{ content: 'Total Batteries by Type', colSpan: 4, styles: {
                    fillColor: _C.accent, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9,
                } }],
                ['Battery Type', 'Devices', 'Total Cells', '% of Devices'],
            ],
            body: battRows.map(([t, d, c]) => [
                t, d, c,
                battDevices.length > 0 ? Math.round((d / battDevices.length) * 100) + '%' : '-',
            ]),
            columnStyles: {
                0: { cellWidth: 'auto' },
                1: { cellWidth: 25, halign: 'right', fontStyle: 'bold' },
                2: { cellWidth: 28, halign: 'right' },
                3: { cellWidth: 28, halign: 'right' },
            },
        });
        y = doc.lastAutoTable.finalY + 5;
    }

    // ══ Section 9: Labels ═════════════════════════════════════════════════════
    const labelCount = {};
    devices.forEach(d => {
        (d.labels || []).forEach(lid => {
            const lo   = labelMap.get(String(lid || '').trim());
            const name = lo ? lo.name : (String(lid || '') || 'Unknown');
            labelCount[name] = (labelCount[name] || 0) + 1;
        });
    });
    const labelRows = Object.entries(labelCount).sort((a, b) => b[1] - a[1]).map(([n, c]) => [n, c]);
    if (labelRows.length) {
        sectionTable('Devices by Label', ['Label', 'Devices', '% of Total'], labelRows, totalAll, y);
        y = doc.lastAutoTable.finalY + 5;
    }

    // ══ Section 10: Device alert lists ════════════════════════════════════════
    const _deviceList = (title, filtered, titleColor, includeAreaBreakdown = false) => {
        if (!filtered.length) return;
        const listRows = filtered.map((d) => {
            if (includeAreaBreakdown) {
                return [
                    d.name || 'Unnamed',
                    d.brand || '-',
                    _resolveAreaName(d.controlledArea, '-'),
                    _resolveAreaName(d.area, '-')
                ];
            }
            const area = areaMap.get(d.controlledArea || d.area || '');
            return [d.name || 'Unnamed', d.brand || '-', area ? area.name : '-'];
        });
        const headers = includeAreaBreakdown
            ? ['Device Name', 'Brand', 'Controlled Area', 'Installed Area']
            : ['Device Name', 'Brand', 'Area'];
        const colStyles = includeAreaBreakdown
            ? { 0: { cellWidth: 'auto' }, 1: { cellWidth: 30 }, 2: { cellWidth: 36 }, 3: { cellWidth: 36 } }
            : { 0: { cellWidth: 'auto' }, 1: { cellWidth: 38 }, 2: { cellWidth: 40 } };
        doc.autoTable({
            ...base,
            startY: doc.lastAutoTable.finalY + 5,
            head: [
                [{ content: `${title} (${filtered.length})`, colSpan: headers.length, styles: {
                    fillColor: titleColor, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9,
                } }],
                headers,
            ],
            body: listRows,
            columnStyles: colStyles,
        });
    };

    const pending    = devices.filter(d => d.status === 'pending');
    const notWorking = devices.filter(d => d.status === 'not-working');

    _deviceList('Pending Devices',     pending,     _C.pending, true);
    _deviceList('Not Working Devices', notWorking,  _C.notWorking);
}

// ─── Device inventory table ────────────────────────────────────────────────────

function _pdfDeviceTable(doc, data, { settings }) {
    doc.addPage();

    const { devices, areas, floors } = data;
    const areaMap  = new Map((areas  || []).map(a => [a.id, a]));
    const floorMap = new Map((floors || []).map(f => [f.id, f]));

    const rows = (devices || []).map(d => {
        const area      = areaMap.get(d.controlledArea || d.area || '');
        const areaName  = area ? area.name : (d.controlledArea || d.area || '-');
        const floorObj  = area && area.floor ? floorMap.get(area.floor) : null;
        const floorName = floorObj ? floorObj.name : '-';

        const brand = (settings && settings.brands)
            ? (getFriendlyOption(settings.brands, d.brand, formatDeviceType) || '-')
            : (d.brand || '-');
        const type  = (settings && settings.types)
            ? (getFriendlyOption(settings.types,  d.type,  formatDeviceType) || '-')
            : _fmtType(d.type);

        return [
            d.name || 'Unnamed',
            brand,
            type,
            _fmtConnectivity(d.connectivity),
            areaName,
            floorName,
            _STATUS_LABELS[d.status] || (d.status || 'Working'),
            d.ip    || '-',
            d.power ? _fmtPower(d.power) : '-',
        ];
    });

    // Column widths sum to _PDF_CW = 182 mm
    doc.autoTable({
        startY: _PDF_HEADER_H + 1,
        head:   [['Name', 'Brand', 'Type', 'Connectivity', 'Area', 'Floor', 'Status', 'IP', 'Power']],
        body:   rows,
        theme:  'grid',
        styles: {
            fontSize: 7.4,
            cellPadding: 1.9,
            overflow: 'linebreak',
            font: 'helvetica',
            lineColor: _C.tableGrid,
            lineWidth: 0.1,
            textColor: _C.textOnLight,
        },
        headStyles: {
            fillColor: _C.tableHead,
            textColor: _C.textLight,
            fontStyle: 'bold',
            fontSize: 7.8,
            lineColor: _C.tableHead,
            lineWidth: 0.1,
        },
        alternateRowStyles: { fillColor: _C.rowAlt },
        columnStyles: {
            0: { cellWidth: 30 },
            1: { cellWidth: 22 },
            2: { cellWidth: 20 },
            3: { cellWidth: 24 },
            4: { cellWidth: 20 },
            5: { cellWidth: 14 },
            6: { cellWidth: 20 },
            7: { cellWidth: 18 },
            8: { cellWidth: 14 },
        },
        didParseCell: function (data) {
            if (data.section !== 'body' || data.column.index !== 6) return;
            const raw = String(data.cell.raw || '').toLowerCase();
            if      (raw === 'working')     data.cell.styles.textColor = _C.working;
            else if (raw === 'pending')     data.cell.styles.textColor = _C.pending;
            else if (raw === 'not working') data.cell.styles.textColor = _C.notWorking;
            else if (raw === 'wishlist')    data.cell.styles.textColor = _C.wishlist;
            data.cell.styles.fontStyle = 'bold';
        },
        margin:      { top: _PDF_HEADER_H + 1, left: _PDF_MARGIN, right: _PDF_MARGIN, bottom: _PDF_BOTTOM_MARGIN },
        didDrawPage: () => _drawPageHeader(doc, 'Device Inventory'),
    });
}

// ─── Connections list ──────────────────────────────────────────────────────────

function _pdfConnectionsPage(doc, data) {
    const { devices } = data;
    const deviceMap   = new Map((devices || []).map(d => [d.id, d]));

    const rows = [];
    (devices || []).forEach(device => {
        if (!Array.isArray(device.ports)) return;
        device.ports.forEach(port => {
            if (!port.connectedTo) return;
            const target     = deviceMap.get(port.connectedTo);
            const targetName = (target && target.name) ? target.name : port.connectedTo;
            const portLabel  = _PORT_LABELS[port.type] || port.type || '-';
            const cable      = [
                port.cableType ? String(port.cableType).toUpperCase() : '',
                port.speed     ? String(port.speed) : '',
            ].filter(Boolean).join(' ');
            rows.push([device.name || 'Unnamed', targetName, portLabel, cable || '-']);
        });
    });

    if (!rows.length) return;

    doc.addPage();
    doc.autoTable({
        startY: _PDF_HEADER_H + 1,
        head:   [['Device', 'Connected To', 'Connection Type', 'Cable Details']],
        body:   rows,
        theme:  'grid',
        styles:             {
            fontSize: 8.2,
            cellPadding: 2.2,
            overflow: 'linebreak',
            lineColor: _C.tableGrid,
            lineWidth: 0.12,
            textColor: _C.textOnLight,
        },
        headStyles:         {
            fillColor: _C.tableHead,
            textColor: _C.textLight,
            fontStyle: 'bold',
            lineColor: _C.tableHead,
            lineWidth: 0.12,
        },
        alternateRowStyles: { fillColor: _C.rowAlt },
        columnStyles: {
            0: { cellWidth: 'auto' },
            1: { cellWidth: 'auto' },
            2: { cellWidth: 34 },
            3: { cellWidth: 30 },
        },
        margin:      { top: _PDF_HEADER_H + 1, left: _PDF_MARGIN, right: _PDF_MARGIN, bottom: _PDF_BOTTOM_MARGIN },
        didDrawPage: () => _drawPageHeader(doc, 'Network Connections'),
    });
}

// ─── Diagram page ──────────────────────────────────────────────────────────────

const _CONN_TYPE_LABELS = {
    ethernet: 'Ethernet',
    usb:      'USB',
    power:    'Power',
    wifi:     'Wi-Fi',
    zigbee:   'Zigbee',
    zwave:    'Z-Wave',
};

async function _pdfDiagramPage(doc, data) {
    const bgFile = await getUiPreference('diagramBackground').catch(() => null);
    const hasBg  = bgFile && bgFile.path;

    let rawPositions = {};
    try {
        rawPositions = hasBg
            ? (await window.loadMapImagePositions() || {})
            : (await window.loadMapPositions()      || {});
    } catch (_) {}

    const deviceMap     = new Map((data.devices || []).map(d => [String(d.id), d]));
    const positionedIds = Object.keys(rawPositions).filter(id => deviceMap.has(id));

    if (!hasBg && !positionedIds.length) return;

    // ── Pre-load background image once ────────────────────────────────────────
    let bgDataUrl = null;
    let bgImgType = 'JPEG';

    if (hasBg) {
        try {
            const url  = buildAppUrl('api/device-files/content')
                + '?path=' + encodeURIComponent(String(bgFile.path));
            const resp = await fetch(url);
            if (resp.ok) bgDataUrl = await _blobToDataUrl(await resp.blob());
        } catch (e) {
            console.warn('[pdf-export] Background load failed:', e.message);
        }
    }

    if (bgDataUrl) {
        const mimeMatch = bgDataUrl.match(/^data:(image\/[a-zA-Z+]+);/);
        const raw = (mimeMatch ? mimeMatch[1].split('/')[1] : 'jpeg').toUpperCase();
        bgImgType = raw === 'JPG' ? 'JPEG' : raw;
    }

    // ── Compute draw area (aspect-ratio preserving) ───────────────────────────
    const CX = _PDF_MARGIN;
    const CY = _PDF_HEADER_H + 5;
    const CW = _PDF_CW;
    const legendY = _PDF_FOOTER_Y - 14;
    const CH = Math.max(140, legendY - CY - 5);

    let drawX = CX, drawY = CY, drawW = CW, drawH = CH;
    if (bgDataUrl) {
        try {
            const dims  = await _imgNaturalSize(bgDataUrl);
            const ratio = dims.width / dims.height;
            drawH = CW / ratio;
            if (drawH > CH) { drawH = CH; drawW = CH * ratio; }
            drawX = CX + (CW - drawW) / 2;
        } catch (_) {}
    }

    // ── Detect active connection types among positioned (non-wishlist) devices ─
    const validIds = positionedIds.filter(id => {
        const d = deviceMap.get(id);
        return d && d.status !== 'wishlist';
    });
    const posSet = new Set(validIds);

    const activeTypes = new Set();
    (data.devices || []).forEach(device => {
        if (!posSet.has(String(device.id))) return;
        if (Array.isArray(device.ports)) {
            device.ports.forEach(port => {
                if (!port.connectedTo || !posSet.has(String(port.connectedTo))) return;
                const kind = (port.type || '').split('-')[0];
                if (kind) activeTypes.add(kind);
            });
        }
        if (device.wifiAccessPointId   && posSet.has(String(device.wifiAccessPointId)))   activeTypes.add('wifi');
        if (device.zigbeeParentId       && posSet.has(String(device.zigbeeParentId)))       activeTypes.add('zigbee');
        if (device.zwaveControllerId    && posSet.has(String(device.zwaveControllerId)))    activeTypes.add('zwave');
    });

    // Order connection types: wired first, wireless last
    const typeOrder = ['ethernet', 'usb', 'power', 'wifi', 'zigbee', 'zwave'];
    const connTypesToDraw = typeOrder.filter(t => activeTypes.has(t));

    // ── Render one page per diagram ───────────────────────────────────────────
    const _drawDiagramPage = (connType, heading) => {
        doc.addPage();
        _drawPageCanvas(doc);
        _drawPageHeader(doc, heading);

        doc.setFillColor(..._C.cardBg);
        doc.setDrawColor(..._C.cardBorder);
        doc.setLineWidth(0.25);
        doc.roundedRect(CX - 1.5, CY - 1.5, CW + 3, CH + 3, 3, 3, 'FD');

        if (bgDataUrl) {
            doc.addImage(bgDataUrl, bgImgType, drawX, drawY, drawW, drawH);
        }

        if (positionedIds.length) {
            const isOverview = connType === null;
            _renderDiagramOverlay(doc, data, rawPositions, positionedIds, drawX, drawY, drawW, drawH, connType, isOverview, !!bgDataUrl);
            if (isOverview) {
                // Status legend only — no connection lines
                _drawDiagramLegend(doc, legendY, new Set());
            } else {
                _drawDiagramLegend(doc, legendY, new Set([connType]));
            }
        }
    };

    // Always render the overview first (all devices, no connections, no legend)
    _drawDiagramPage(null, 'Diagram — Overview');

    // Then one page per active connection type
    for (const connType of connTypesToDraw) {
        _drawDiagramPage(connType, `Network Diagram — ${_CONN_TYPE_LABELS[connType] || connType}`);
    }
}

// App-matching status colours for diagram nodes (match Cytoscape getDeviceStatusColor)
const _DIAGRAM_STATUS_COLOR = {
    'working':     [16, 185, 129],   // #10b981 emerald-500
    'pending':     [245, 158,  11],  // #f59e0b amber-500
    'not-working': [239,  68,  68],  // #ef4444 red-500
};

/** Draws a filled arrowhead tip at (tx,ty) pointing from (fx,fy). */
function _drawArrowHead(doc, fx, fy, tx, ty, color, size) {
    const angle  = Math.atan2(ty - fy, tx - fx);
    const spread = Math.PI / 6;  // 30°
    const p1x = tx - size * Math.cos(angle - spread);
    const p1y = ty - size * Math.sin(angle - spread);
    const p2x = tx - size * Math.cos(angle + spread);
    const p2y = ty - size * Math.sin(angle + spread);
    doc.setFillColor(...color);
    doc.lines(
        [[p1x - tx, p1y - ty], [p2x - p1x, p2y - p1y], [tx - p2x, ty - p2y]],
        tx, ty, [1, 1], 'F', true
    );
}

/**
 * @param {string|null} filterType  If set, only connections of this type are drawn.
 *                                   Pass null to draw all connections (or none if no connections exist).
 */
function _renderDiagramOverlay(doc, data, rawPositions, positionedIds, areaX, areaY, areaW, areaH, filterType, noConnections = false, hasBackground = true) {
    if (!positionedIds.length || !areaW || !areaH) return;

    const deviceMap = new Map((data.devices || []).map(d => [String(d.id), d]));

    // Wishlist devices are not shown on the diagram (same as the app)
    const validIds = positionedIds.filter(id => {
        const d = deviceMap.get(id);
        return d && d.status !== 'wishlist';
    });
    if (!validIds.length) return;

    // ── Normalise positions to 0–1 ────────────────────────────────────────────
    const isNormalized = validIds.some(
        id => rawPositions[id] && rawPositions[id].coordinateSpace === 'background-normalized'
    );

    let normPos;
    if (isNormalized) {
        // Background-normalized coords already are 0–1 fractions of the image.
        // Map them directly to the image area without extra padding.
        normPos = validIds.reduce((acc, id) => {
            acc[id] = { x: rawPositions[id].x, y: rawPositions[id].y };
            return acc;
        }, {});
    } else {
        const xs = validIds.map(id => rawPositions[id].x);
        const ys = validIds.map(id => rawPositions[id].y);
        const x0 = Math.min(...xs), x1 = Math.max(...xs);
        const y0 = Math.min(...ys), y1 = Math.max(...ys);
        const rX = (x1 - x0) || 1, rY = (y1 - y0) || 1;
        const PAD = 0.05; // 5% inset when using raw pixel bounding box
        normPos = validIds.reduce((acc, id) => {
            acc[id] = {
                x: PAD + ((rawPositions[id].x - x0) / rX) * (1 - PAD * 2),
                y: PAD + ((rawPositions[id].y - y0) / rY) * (1 - PAD * 2),
            };
            return acc;
        }, {});
    }

    const toPdfX = nx => areaX + nx * areaW;
    const toPdfY = ny => areaY + ny * areaH;

    const nodeW  = Math.max(14, Math.min(26, areaW * 0.07));
    const nodeH  = Math.max(7,  Math.min(11, nodeW * 0.42));
    const nodeRx = nodeW * 0.08;

    const posSet = new Set(validIds);

    // ── Build deduplicated connection list ────────────────────────────────────
    const drawnConns = new Set();
    const connections = [];

    if (noConnections) { /* skip — overview page shows devices only */ }
    else (data.devices || []).forEach(device => {
        if (!posSet.has(String(device.id))) return;
        const sid = String(device.id || '');

        // Port connections: ethernet / usb / power  → solid + arrowhead
        if (Array.isArray(device.ports)) {
            device.ports.forEach(port => {
                if (!port.connectedTo) return;
                const tid = String(port.connectedTo);
                if (!posSet.has(tid)) return;
                const kind = (port.type || '').split('-')[0];
                if (filterType && kind !== filterType) return;
                // Direction: output ports = from this device; input ports = to this device
                const isOutput = (port.type || '').includes('-output');
                const [fromId, toId] = isOutput ? [sid, tid] : [tid, sid];
                const key = [fromId, toId].sort().join('|') + '|' + kind;
                if (drawnConns.has(key)) return;
                drawnConns.add(key);

                let label = '';
                if (kind === 'ethernet') {
                    // Match app: "Cat6 (1 Gbps)" or "Cat6" or "Ethernet (1 Gbps)" or "Ethernet"
                    const cable = port.cableType ? String(port.cableType).replace(/^cat/i, 'Cat') : '';
                    const speed = port.speed ? String(port.speed) : '';
                    if (cable && speed) label = `${cable} (${speed})`;
                    else if (cable)     label = cable;
                    else if (speed)     label = `Ethernet (${speed})`;
                    else                label = 'Ethernet';
                } else if (kind === 'usb') {
                    label = 'USB';
                } else if (kind === 'power') {
                    // Match app: show consumer device's meanConsumption, fallback "Power"
                    const consumerId = (port.type || '').includes('power-input') ? sid : tid;
                    const consumer   = deviceMap.get(consumerId);
                    const watts      = consumer && consumer.meanConsumption != null
                        ? String(consumer.meanConsumption).trim().replace(/\s*w$/i, '') + ' W'
                        : null;
                    label = watts || 'Power';
                }
                connections.push({ fromId, toId, type: kind, label, arrow: true, dashed: false });
            });
        }

        // Wi-Fi → access point (no arrowhead, dashed)
        const wapId = String(device.wifiAccessPointId || '').trim();
        if (!filterType || filterType === 'wifi')
        if (wapId && wapId !== sid && posSet.has(wapId)) {
            const key = [sid, wapId].sort().join('|') + '|wifi';
            if (!drawnConns.has(key)) {
                drawnConns.add(key);
                connections.push({ fromId: sid, toId: wapId, type: 'wifi', label: '', arrow: false, dashed: true });
            }
        }

        // Zigbee → parent (no arrowhead, dashed)
        const zbId = String(device.zigbeeParentId || '').trim();
        if (!filterType || filterType === 'zigbee')
        if (zbId && zbId !== sid && posSet.has(zbId)) {
            const key = [sid, zbId].sort().join('|') + '|zigbee';
            if (!drawnConns.has(key)) {
                drawnConns.add(key);
                connections.push({ fromId: sid, toId: zbId, type: 'zigbee', label: '', arrow: false, dashed: true });
            }
        }

        // Z-Wave → controller (no arrowhead, dashed)
        const zwId = String(device.zwaveControllerId || '').trim();
        if (!filterType || filterType === 'zwave')
        if (zwId && zwId !== sid && posSet.has(zwId)) {
            const key = [sid, zwId].sort().join('|') + '|zwave';
            if (!drawnConns.has(key)) {
                drawnConns.add(key);
                connections.push({ fromId: sid, toId: zwId, type: 'zwave', label: '', arrow: false, dashed: true });
            }
        }
    });

    // ── Compute participating nodes ───────────────────────────────────────────
    const participatingIds = filterType
        ? new Set(connections.flatMap(c => [c.fromId, c.toId]))
        : new Set(validIds);

    // ── Area / floor outlines when no background image ────────────────────────
    // Drawn FIRST so they sit behind connection lines and device nodes.
    // Uses participatingIds so per-connection diagrams only show boxes for
    // areas/floors that actually have visible devices on this page.
    if (!hasBackground && (data.areas || []).length) {
        const areaMap  = new Map((data.areas  || []).map(a => [String(a.id), a]));
        const floorMap = new Map((data.floors || []).map(f => [String(f.id), f]));

        const halfW = nodeW / 2, halfH = nodeH / 2;
        const LBL_H = 5;   // mm reserved for label above box
        const PAD_A = 3.5; // mm padding: area around device half-extents
        const PAD_F = 4;   // mm padding: floor around area boxes

        // Per-area bounding box, computed only from participating devices
        const areaBboxes = {};
        validIds.filter(id => participatingIds.has(id)).forEach(id => {
            const device = deviceMap.get(id);
            const areaId = device && device.area ? String(device.area) : '__no_area__';
            const px = toPdfX(normPos[id].x), py = toPdfY(normPos[id].y);
            if (!areaBboxes[areaId]) {
                areaBboxes[areaId] = { x1: px, y1: py, x2: px, y2: py };
            } else {
                const b = areaBboxes[areaId];
                b.x1 = Math.min(b.x1, px); b.y1 = Math.min(b.y1, py);
                b.x2 = Math.max(b.x2, px); b.y2 = Math.max(b.y2, py);
            }
        });
        // Expand by half-node + area padding; also leave room above for the label
        Object.values(areaBboxes).forEach(b => {
            b.x1 -= halfW + PAD_A;
            b.y1 -= halfH + PAD_A + LBL_H; // extra space at top for label
            b.x2 += halfW + PAD_A;
            b.y2 += halfH + PAD_A;
        });

        // Per-floor bounding box from area boxes
        const floorBboxes = {};
        Object.entries(areaBboxes).forEach(([areaId, b]) => {
            const area   = areaMap.get(areaId);
            const floorId = area && area.floor && floorMap.has(String(area.floor))
                ? String(area.floor)
                : '__no_floor__';
            if (!floorBboxes[floorId]) {
                floorBboxes[floorId] = { x1: b.x1, y1: b.y1, x2: b.x2, y2: b.y2 };
            } else {
                const f = floorBboxes[floorId];
                f.x1 = Math.min(f.x1, b.x1); f.y1 = Math.min(f.y1, b.y1);
                f.x2 = Math.max(f.x2, b.x2); f.y2 = Math.max(f.y2, b.y2);
            }
        });
        Object.values(floorBboxes).forEach(b => {
            b.x1 -= PAD_F; b.y1 -= PAD_F + LBL_H; // extra space at top for label
            b.x2 += PAD_F; b.y2 += PAD_F;
        });

        // Draw floors (solid blue border + light fill; label above the top edge)
        Object.entries(floorBboxes).forEach(([floorId, b]) => {
            const floor  = floorMap.get(floorId);
            const label  = floor ? floor.name : 'No Floor';
            const bx = b.x1, by = b.y1 + LBL_H, bw = b.x2 - b.x1, bh = b.y2 - b.y1 - LBL_H;
            doc.setFillColor(226, 232, 240);  // slate-200
            doc.setDrawColor(59, 130, 246);   // blue-500
            doc.setLineWidth(floorId === '__no_floor__' ? 0.3 : 0.5);
            doc.setLineDashPattern(floorId === '__no_floor__' ? [2, 1.2] : [], 0);
            doc.roundedRect(bx, by, bw, bh, 1.5, 1.5, 'FD');
            doc.setLineDashPattern([], 0);
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(5.5);
            doc.setTextColor(59, 130, 246);
            doc.text(label, bx + bw / 2, by - 1.5, { align: 'center', baseline: 'bottom' });
        });

        // Draw areas (dashed gray border; label above the top edge)
        Object.entries(areaBboxes).forEach(([areaId, b]) => {
            const area  = areaMap.get(areaId);
            const label = area ? area.name : 'No Area';
            const bx = b.x1, by = b.y1 + LBL_H, bw = b.x2 - b.x1, bh = b.y2 - b.y1 - LBL_H;
            doc.setDrawColor(100, 116, 139);  // slate-500
            doc.setLineWidth(0.3);
            doc.setLineDashPattern([1.5, 1], 0);
            doc.roundedRect(bx, by, bw, bh, 1.2, 1.2, 'S');
            doc.setLineDashPattern([], 0);
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(4.5);
            doc.setTextColor(100, 116, 139);
            doc.text(label, bx + bw / 2, by - 1, { align: 'center', baseline: 'bottom' });
        });
    }

    // ── Draw connection lines + arrows ────────────────────────────────────────
    const _connColor = {
        ethernet: _C.connEthernet,
        usb:      _C.connUsb,
        power:    _C.connPower,
        wifi:     _C.connWifi,
        zigbee:   _C.connZigbee,
        zwave:    _C.connZwave,
    };

    const placedLabels = [];

    connections.forEach(conn => {
        const np = normPos[conn.fromId];
        const nt = normPos[conn.toId];
        if (!np || !nt) return;

        const fx = toPdfX(np.x), fy = toPdfY(np.y);
        const tx = toPdfX(nt.x), ty = toPdfY(nt.y);
        const color   = _connColor[conn.type] || _C.connDefault;
        const arrowSz = 2.2;
        const lineW   = 0.45;

        const angle    = Math.atan2(ty - fy, tx - fx);
        const lineEndX = conn.arrow ? tx - arrowSz * Math.cos(angle) : tx;
        const lineEndY = conn.arrow ? ty - arrowSz * Math.sin(angle) : ty;

        doc.setDrawColor(...color);
        doc.setLineWidth(lineW);
        if (conn.dashed) doc.setLineDashPattern([2.5, 1.5], 0);
        doc.line(fx, fy, lineEndX, lineEndY);
        if (conn.dashed) doc.setLineDashPattern([], 0);

        if (conn.arrow) _drawArrowHead(doc, fx, fy, tx, ty, color, arrowSz);

        if (conn.label) {
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(3.0);
            const textW  = doc.getTextWidth(conn.label);
            const badgeW = textW + 2.2;
            const badgeH = 2.8;

            const mx = fx + (tx - fx) * 0.5;
            const my = fy + (ty - fy) * 0.5;
            const dx = tx - fx, dy = ty - fy;
            const len = Math.sqrt(dx * dx + dy * dy) || 1;
            const pnx = -dy / len, pny = dx / len;
            const perpOffsets = [0, 3, -3, 6, -6];
            let lx = mx, ly = my;
            for (const off of perpOffsets) {
                const cx = mx + pnx * off;
                const cy = my + pny * off;
                const overlaps = placedLabels.some(lb =>
                    Math.abs(cx - lb.cx) < (badgeW + lb.w) / 2 + 1.5 &&
                    Math.abs(cy - lb.cy) < (badgeH + lb.h) / 2 + 1.0
                );
                if (!overlaps) { lx = cx; ly = cy; break; }
            }
            placedLabels.push({ cx: lx, cy: ly, w: badgeW, h: badgeH });

            doc.setFillColor(..._C.coverBg);
            doc.setDrawColor(...color);
            doc.setLineWidth(0.25);
            doc.roundedRect(lx - badgeW / 2, ly - badgeH / 2, badgeW, badgeH, 0.8, 0.8, 'FD');
            doc.setTextColor(...color);
            doc.text(conn.label, lx, ly, { align: 'center', baseline: 'middle' });
        }
    });

    // ── Device nodes ──────────────────────────────────────────────────────────
    validIds.filter(id => participatingIds.has(id)).forEach(id => {
        const device = deviceMap.get(id);
        if (!device) return;

        const px     = toPdfX(normPos[id].x);
        const py     = toPdfY(normPos[id].y);
        const border = _DIAGRAM_STATUS_COLOR[device.status] || _C.accent;

        // Card background — dark fill + status-coloured border (same as app SVG card)
        doc.setFillColor(..._C.headerBg);
        doc.setDrawColor(...border);
        doc.setLineWidth(0.6);
        doc.roundedRect(px - nodeW / 2, py - nodeH / 2, nodeW, nodeH, nodeRx, nodeRx, 'FD');

        // Device name — 2 lines max, white text
        const fsize   = Math.max(3.2, Math.min(4.2, nodeW * 0.18));
        const textW   = nodeW - 3;
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(fsize);
        doc.setTextColor(241, 245, 249);  // #f1f5f9 — matches app SVG text
        const allLines = doc.splitTextToSize(device.name || 'Unnamed', textW);
        const display  = allLines.slice(0, 2);
        const lineH    = fsize * 0.42;
        const topY     = py - (display.length - 1) * lineH / 2;
        display.forEach((ln, li) => {
            doc.text(ln, px, topY + li * lineH, { align: 'center', baseline: 'middle' });
        });
    });
}

function _drawDiagramLegend(doc, y, activeTypes) {
    // Status nodes (wishlist excluded — not shown in diagram)
    const nodeItems = [
        { color: _DIAGRAM_STATUS_COLOR['working'],     label: 'Working'     },
        { color: _DIAGRAM_STATUS_COLOR['pending'],     label: 'Pending'     },
        { color: _DIAGRAM_STATUS_COLOR['not-working'], label: 'Not Working' },
    ];

    // Connection lines — only show types that actually appear in this diagram
    const allLineItems = [
        { color: _C.connEthernet, label: 'Ethernet', type: 'ethernet', dashed: false },
        { color: _C.connUsb,      label: 'USB',       type: 'usb',      dashed: false },
        { color: _C.connPower,    label: 'Power',     type: 'power',    dashed: false },
        { color: _C.connWifi,     label: 'Wi-Fi',     type: 'wifi',     dashed: true  },
        { color: _C.connZigbee,   label: 'Zigbee',    type: 'zigbee',   dashed: true  },
        { color: _C.connZwave,    label: 'Z-Wave',    type: 'zwave',    dashed: true  },
    ];
    const lineItems = activeTypes
        ? allLineItems.filter(it => activeTypes.has(it.type))
        : allLineItems;

    const boxX = _PDF_MARGIN - 1;
    const boxY = y - 2;
    const boxW = _PDF_CW + 2;
    const boxH = 13;
    doc.setFillColor(..._C.cardBg);
    doc.setDrawColor(..._C.cardBorder);
    doc.setLineWidth(0.2);
    doc.roundedRect(boxX, boxY, boxW, boxH, 2, 2, 'FD');

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6);
    const swatchW = 5;
    const itemGap = 2.2;
    let x = _PDF_MARGIN + 1;
    let rowY = y + 1.4;

    nodeItems.forEach(item => {
        const lblW = doc.getTextWidth(item.label);
        const itemW = swatchW + 1 + lblW + itemGap + 2;
        if (x + itemW > _PDF_W - _PDF_MARGIN) {
            rowY += 4;
            x = _PDF_MARGIN + 1;
        }
        doc.setFillColor(...item.color);
        doc.roundedRect(x, rowY - 1.8, swatchW, 3, 0.8, 0.8, 'F');
        doc.setTextColor(..._C.textOnLight);
        doc.text(item.label, x + swatchW + 1, rowY + 0.7);
        x += itemW;
    });

    x += 3;

    lineItems.forEach(item => {
        const lblW = doc.getTextWidth(item.label);
        const itemW = swatchW + 1 + lblW + itemGap + 2;
        if (x + itemW > _PDF_W - _PDF_MARGIN) {
            rowY += 4;
            x = _PDF_MARGIN + 1;
        }
        doc.setDrawColor(...item.color);
        doc.setLineWidth(0.65);
        if (item.dashed) doc.setLineDashPattern([1.5, 1.2], 0);
        doc.line(x, rowY - 0.3, x + swatchW, rowY - 0.3);
        if (item.dashed) doc.setLineDashPattern([], 0);
        if (!item.dashed) {
            _drawArrowHead(doc, x, rowY - 0.3, x + swatchW, rowY - 0.3, item.color, 1.2);
        }
        doc.setTextColor(..._C.textOnLight);
        doc.text(item.label, x + swatchW + 1, rowY + 0.7);
        x += itemW;
    });
}

// ─── Footers ───────────────────────────────────────────────────────────────────

function _pdfFooters(doc) {
    const total = doc.getNumberOfPages();
    for (let i = 2; i <= total; i++) {
        doc.setPage(i);
        doc.setDrawColor(..._C.pageBorder);
        doc.setLineWidth(0.25);
        doc.line(_PDF_MARGIN, _PDF_FOOTER_Y, _PDF_W - _PDF_MARGIN, _PDF_FOOTER_Y);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7.2);
        doc.setTextColor(..._C.textOnLight);
        doc.text(_FOOTER_TEXT, _PDF_MARGIN, _PDF_FOOTER_Y + 4.5);

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(7);
        doc.setTextColor(..._C.accentDark);
        doc.text(`Page ${i - 1}/${total - 1}`, _PDF_W - _PDF_MARGIN, _PDF_FOOTER_Y + 4.5, { align: 'right' });
    }
}

// ─── Page header renderer ──────────────────────────────────────────────────────

function _drawPageHeader(doc, title) {
    const W     = _PDF_W;
    const bandH = _PDF_HEADER_H - 3;

    // Full-color band
    doc.setFillColor(..._C.headerBg);
    doc.rect(0, 0, W, bandH, 'F');

    // Accent strip and decorative right block
    doc.setFillColor(..._C.accent);
    doc.rect(0, 0, 4, bandH, 'F');
    doc.setFillColor(..._C.accentDark);
    doc.roundedRect(W - 34, 0, 34, bandH, 0, 0, 'F');

    // Subtle inner highlight for depth
    doc.setDrawColor(255, 255, 255);
    doc.setLineWidth(0.15);
    doc.line(4, 4.4, W - 6, 4.4);

    const maxTitleW = W - (_PDF_MARGIN * 2 + 54);
    const titleLine = doc.splitTextToSize(String(title || ''), maxTitleW)[0] || '';
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10.4);
    doc.setTextColor(..._C.textLight);
    doc.text(titleLine, _PDF_MARGIN, bandH / 2 + 2, { baseline: 'middle' });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6.6);
    doc.setTextColor(..._C.textLight);
    doc.text('Smart Home Planner', W - _PDF_MARGIN, bandH / 2 + 2, {
        align: 'right',
        baseline: 'middle',
    });

    doc.setDrawColor(..._C.pageBorder);
    doc.setLineWidth(0.35);
    doc.line(0, bandH, W, bandH);
}

// ─── Utilities ─────────────────────────────────────────────────────────────────

function _groupBy(arr, keyFn) {
    return (arr || []).reduce((acc, item) => {
        const key = String(keyFn(item) || '');
        if (!acc[key]) acc[key] = [];
        acc[key].push(item);
        return acc;
    }, {});
}

function _fmtConnectivity(value) {
    if (!value) return '-';
    return typeof formatConnectivity === 'function' ? formatConnectivity(value) : String(value);
}

function _fmtType(value) {
    if (!value) return '-';
    return typeof formatDeviceType === 'function' ? formatDeviceType(value) : String(value);
}

function _fmtPower(value) {
    const v = String(value || '').toLowerCase();
    if (v === 'wired')   return 'Wired';
    if (v === 'battery') return 'Battery';
    return value || '-';
}

function _blobToDataUrl(blob) {
    return new Promise((resolve, reject) => {
        const reader   = new FileReader();
        reader.onload  = () => resolve(reader.result);
        reader.onerror = () => reject(new Error('FileReader failed'));
        reader.readAsDataURL(blob);
    });
}

/** Fetches a URL and returns a base64 data URL, or throws on failure. */
async function _fetchDataUrl(url) {
    const resp = await fetch(url);
    if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
    return _blobToDataUrl(await resp.blob());
}

function _imgNaturalSize(dataUrl) {
    return new Promise((resolve, reject) => {
        const img   = new Image();
        img.onload  = () => resolve({ width: img.naturalWidth, height: img.naturalHeight });
        img.onerror = () => reject(new Error('Image load failed'));
        img.src     = dataUrl;
    });
}

// ─── Pie chart helpers ─────────────────────────────────────────────────────────

/**
 * Draws a filled polygon approximating a pie sector.
 * Angles in radians; 0 = right, −π/2 = top (same as Math.cos/sin convention).
 */
function _drawPieSlice(doc, cx, cy, r, startAngle, endAngle, color) {
    const span = endAngle - startAngle;
    if (Math.abs(span) < 0.001) return;
    const steps = Math.max(6, Math.ceil(Math.abs(span) * 10));

    // Build relative-coordinate segments for doc.lines():
    // Start from center → arc start → arc steps → back to center
    const segs = [];
    const ax0  = cx + Math.cos(startAngle) * r;
    const ay0  = cy + Math.sin(startAngle) * r;
    segs.push([ax0 - cx, ay0 - cy]); // center → arc start

    for (let i = 1; i <= steps; i++) {
        const a   = startAngle + span * i / steps;
        const pa  = startAngle + span * (i - 1) / steps;
        segs.push([
            (cx + Math.cos(a) * r) - (cx + Math.cos(pa) * r),
            (cy + Math.sin(a) * r) - (cy + Math.sin(pa) * r),
        ]);
    }

    const axN = cx + Math.cos(endAngle) * r;
    const ayN = cy + Math.sin(endAngle) * r;
    segs.push([cx - axN, cy - ayN]); // arc end → center

    doc.setFillColor(...color);
    doc.lines(segs, cx, cy, [1, 1], 'F', true);
}

/**
 * Draws a donut-style pie chart.
 * slices = [{ label, count, color }]
 * total  = denominator (sum of all visible counts, may differ from devices.length)
 */
function _drawPieChart(doc, cx, cy, r, slices, total) {
    if (!slices || !slices.length || !total) return;

    let startAngle = -Math.PI / 2; // start from top
    slices.forEach(slice => {
        if (slice.count <= 0) return;
        const angle = (slice.count / total) * 2 * Math.PI;
        _drawPieSlice(doc, cx, cy, r, startAngle, startAngle + angle, slice.color);
        startAngle += angle;
    });

    // Donut hole (erase centre)
    doc.setFillColor(..._C.cardBg);
    doc.circle(cx, cy, r * 0.44, 'F');
}

/**
 * Draws one chart card.
 */
function _drawPieChartBox(doc, bx, by, bw, bh, title, slices, total) {
    doc.setFillColor(..._C.cardBg);
    doc.roundedRect(bx, by, bw, bh, 3, 3, 'F');

    doc.setFillColor(..._C.cardMutedBg);
    doc.roundedRect(bx + 1, by + 1, bw - 2, 10, 2, 2, 'F');

    doc.setDrawColor(..._C.cardBorder);
    doc.setLineWidth(0.25);
    doc.roundedRect(bx, by, bw, bh, 3, 3, 'D');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.4);
    doc.setTextColor(..._C.textStrong);
    doc.text(title, bx + bw / 2, by + 7, { align: 'center', baseline: 'middle' });

    doc.setDrawColor(..._C.cardBorder);
    doc.setLineWidth(0.2);
    doc.line(bx + 3, by + 11, bx + bw - 3, by + 11);

    if (!slices || !slices.length || !total) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7);
        doc.setTextColor(..._C.textMuted);
        doc.text('No data', bx + bw / 2, by + bh / 2, { align: 'center' });
        return;
    }

    // Donut chart
    const cx = bx + 22;
    const cy = by + 13 + (bh - 13) / 2;
    const r  = 15;
    _drawPieChart(doc, cx, cy, r, slices, total);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(6.8);
    doc.setTextColor(..._C.textStrong);
    doc.text(String(total), cx, cy, { align: 'center', baseline: 'middle' });

    const legX      = bx + 42;
    const legEndX   = bx + bw - 3;
    const legStartY = by + 15;
    const visSlices = slices.filter(s => s.count > 0);
    const lineH     = Math.min(11, (bh - 18) / Math.max(1, visSlices.length));

    visSlices.slice(0, 8).forEach((slice, i) => {
        const midY = legStartY + i * lineH + lineH / 2;
        const pct  = Math.round((slice.count / total) * 100);

        doc.setFillColor(...slice.color);
        doc.roundedRect(legX, midY - 1.5, 3, 3, 0.4, 0.4, 'F');

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(6);
        doc.setTextColor(..._C.textStrong);
        const lbl = slice.label.length > 13 ? slice.label.substring(0, 12) + '…' : slice.label;
        doc.text(lbl, legX + 5, midY + 0.8);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(5.5);
        doc.setTextColor(..._C.textOnLight);
        doc.text(`${slice.count} (${pct}%)`, legEndX, midY + 0.8, { align: 'right' });
    });
}

// ─── Charts page ───────────────────────────────────────────────────────────────

function _pdfChartsPage(doc, data) {
    doc.addPage();
    _drawPageCanvas(doc);
    _drawPageHeader(doc, 'Visual Summary');

    doc.setFillColor(..._C.cardMutedBg);
    doc.roundedRect(_PDF_MARGIN - 1, _PDF_HEADER_H + 2, _PDF_CW + 2, _PDF_H - _PDF_HEADER_H - 17, 4, 4, 'F');

    const { devices } = data;
    const total = devices.length;

    // Distinct colour palette for multi-slice charts
    const PAL = [
        [59, 130, 246], [34, 197,  94], [250, 204,  21], [245, 158,  11],
        [220,  38,  38], [124,  58, 237], [20, 184, 166], [56, 189, 248],
        [239,  68,  68], [168,  85, 247], [14, 165, 233], [100, 116, 139],
    ];

    // ── Compute per-chart slice arrays ────────────────────────────────────────

    const statusSlices = [
        { label: 'Working',     count: devices.filter(d => d.status === 'working').length,     color: _C.working    },
        { label: 'Pending',     count: devices.filter(d => d.status === 'pending').length,     color: _C.pending    },
        { label: 'Not Working', count: devices.filter(d => d.status === 'not-working').length, color: _C.notWorking },
        { label: 'Wishlist',    count: devices.filter(d => d.status === 'wishlist').length,    color: _C.wishlist   },
    ].filter(s => s.count > 0);

    const connSlices = Object.entries(_groupBy(devices.filter(d => d.connectivity), d => d.connectivity))
        .sort((a, b) => b[1].length - a[1].length)
        .map(([k, v], i) => ({ label: _fmtConnectivity(k), count: v.length, color: PAL[i % PAL.length] }));
    const connTotal  = connSlices.reduce((s, x) => s + x.count, 0);

    const powerSlices = [
        { label: 'Wired',   count: devices.filter(d => d.power === 'wired').length,   color: _C.accent   },
        { label: 'Battery', count: devices.filter(d => d.power === 'battery').length, color: [250,204,21] },
        { label: 'Unknown', count: devices.filter(d => !d.power).length,              color: [100, 116, 139] },
    ].filter(s => s.count > 0);
    const powerTotal = powerSlices.reduce((s, x) => s + x.count, 0);

    const wired = devices.filter(d => d.power === 'wired');
    const upsSlices = [
        { label: 'Protected',     count: wired.filter(d => d.upsProtected).length,  color: [34,197,94]   },
        { label: 'Not Protected', count: wired.filter(d => !d.upsProtected).length, color: [100, 116, 139] },
    ].filter(s => s.count > 0);
    const upsTotal = wired.length;

    const intSlices = [
        { label: 'Home Assistant', count: devices.filter(d => Array.isArray(d.haDeviceIds) && d.haDeviceIds.length > 0).length, color: [34,197,94]   },
        { label: 'Google Home',    count: devices.filter(d => d.googleHome).length,         color: [59,130,246]  },
        { label: 'Amazon Alexa',   count: devices.filter(d => d.alexa).length,              color: [56,189,248]  },
        { label: 'Apple HomeKit',  count: devices.filter(d => d.appleHomeKit).length,       color: [100,116,139] },
        { label: 'SmartThings',    count: devices.filter(d => d.samsungSmartThings).length, color: [20,184,166]  },
    ].filter(s => s.count > 0);
    const intTotal = intSlices.reduce((s, x) => s + x.count, 0) || 1;

    const localSlices = [
        { label: '100% Local', count: devices.filter(d => d.localOnly).length,  color: [34,197,94]  },
        { label: 'Cloud',      count: devices.filter(d => !d.localOnly).length, color: [220,38,38]  },
    ].filter(s => s.count > 0);

    // ── Layout: 2 columns × 3 rows ────────────────────────────────────────────
    const colW   = 89;
    const colGap = 4;
    const col0   = _PDF_MARGIN;
    const col1   = _PDF_MARGIN + colW + colGap;
    const rowH   = 82;
    const row0   = _PDF_HEADER_H + 4;

    const charts = [
        { title: 'Device Status',   slices: statusSlices, total                          },
        { title: 'Connectivity',    slices: connSlices,   total: connTotal               },
        { title: 'Power Source',    slices: powerSlices,  total: powerTotal              },
        { title: 'UPS Protection',  slices: upsSlices,    total: upsTotal,               },
        { title: 'Integrations',    slices: intSlices,    total: intTotal                },
        { title: 'Local vs Cloud',  slices: localSlices,  total                          },
    ];

    charts.forEach((chart, i) => {
        const col = i % 2;
        const row = Math.floor(i / 2);
        const bx  = col === 0 ? col0 : col1;
        const by  = row0 + row * rowH;
        _drawPieChartBox(doc, bx, by, colW, rowH - 2, chart.title, chart.slices, chart.total);
    });
}

// ─── Page 2: Table of Contents (drawn last, after all pages are known) ──────────

function _pdfTocPage(doc, tocPages, { houseName, dateStr }) {
    _drawPageCanvas(doc);
    _drawPageHeader(doc, 'Table of Contents');

    const W      = _PDF_W;
    const M      = _PDF_MARGIN;
    const endX   = W - M;

    doc.setFillColor(..._C.cardBg);
    doc.setDrawColor(..._C.cardBorder);
    doc.setLineWidth(0.2);
    doc.roundedRect(M, _PDF_HEADER_H + 4, _PDF_CW, 16, 3, 3, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(..._C.textStrong);
    doc.text('Report Index', M + 4, _PDF_HEADER_H + 10);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(..._C.textOnLight);
    doc.text(`${houseName}  ·  ${dateStr}`, M + 4, _PDF_HEADER_H + 15);

    // Sections definition
    // Display page = pdf page - 1  (cover page 1 is not counted)
    const sections = [
        {
            num:      1,
            title:    'Visual Summary',
            desc:     'Status, connectivity, power source, UPS, integrations & local vs. cloud charts',
            pdfPage:  tocPages.visualSummary,
        },
        {
            num:      2,
            title:    'Summary Report',
            desc:     'Full breakdown by status, connectivity, area, floor, power and integrations',
            pdfPage:  tocPages.summary,
        },
        {
            num:      3,
            title:    'Device Details',
            desc:     'Complete specifications, connections and integration info for every device',
            pdfPage:  tocPages.deviceDetails,
        },
        {
            num:      4,
            title:    'Network Diagrams',
            desc:     'Overview of all devices, then one diagram per connection type',
            pdfPage:  tocPages.diagram,
        },
        {
            num:      5,
            title:    'Test Cases',
            desc:     'Manual test cases grouped by category with steps and expected results',
            pdfPage:  tocPages.testCases,
        },
    ];

    const rowH    = 34;
    const startY  = _PDF_HEADER_H + 24;

    sections.forEach((sec, i) => {
        const rowY    = startY + i * rowH;
        const displayPage = sec.pdfPage - 1; // cover doesn't count

        doc.setFillColor(..._C.cardBg);
        doc.setDrawColor(..._C.cardBorder);
        doc.setLineWidth(0.2);
        doc.roundedRect(M, rowY, _PDF_CW, rowH - 5, 3, 3, 'FD');

        doc.setFillColor(..._C.accent);
        doc.roundedRect(M, rowY, 2.5, rowH - 5, 2, 2, 'F');

        doc.setFillColor(..._C.accentSoft);
        doc.roundedRect(M + 6, rowY + 4, 10, 10, 2, 2, 'F');
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8);
        doc.setTextColor(..._C.accentDark);
        doc.text(String(sec.num), M + 11, rowY + 9.2, { align: 'center', baseline: 'middle' });

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(11.2);
        doc.setTextColor(..._C.textStrong);
        doc.text(sec.title, M + 20, rowY + 9);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7.7);
        doc.setTextColor(..._C.textOnLight);
        const descLines = doc.splitTextToSize(sec.desc, _PDF_CW - 48);
        doc.text(descLines, M + 20, rowY + 14.5);

        const pgBadgeW = 18;
        const pgBadgeH = 10;
        const pgBadgeX = endX - pgBadgeW;
        const pgBadgeY = rowY + 6;
        doc.setFillColor(..._C.cardMutedBg);
        doc.setDrawColor(..._C.cardBorder);
        doc.roundedRect(pgBadgeX, pgBadgeY, pgBadgeW, pgBadgeH, 2, 2, 'FD');
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(10.5);
        doc.setTextColor(..._C.accent);
        doc.text(String(displayPage), pgBadgeX + pgBadgeW / 2, pgBadgeY + pgBadgeH / 2 + 0.4, {
            align: 'center',
            baseline: 'middle',
        });
    });
}

// ─── Device Detail Pages ────────────────────────────────────────────────────────

function _pdfDeviceDetailPages(doc, data, _config) {
    const { devices, areas, floors, labels } = data;
    const areaMap  = new Map((areas  || []).map(a => [a.id, a]));
    const floorMap = new Map((floors || []).map(f => [f.id, f]));
    const labelMap = new Map((labels || []).map(l => [l.id, l]));
    const devMap   = new Map((devices || []).map(d => [String(d.id), d]));

    // Same sort order as index
    const sorted = [...devices].sort((a, b) => {
        const aArea = ((areaMap.get(a.area) || {}).name || '').toLowerCase();
        const bArea = ((areaMap.get(b.area) || {}).name || '').toLowerCase();
        return (aArea + '|' + (a.name || '').toLowerCase())
            .localeCompare(bArea + '|' + (b.name || '').toLowerCase());
    });

    sorted.forEach((device, devIndex) => {
        doc.addPage();

        const devNum      = String(devIndex + 1).padStart(2, '0');
        const area        = areaMap.get(device.area)  || {};
        const floor       = floorMap.get(area.floor)  || {};
        const statusColor = device.status === 'working'     ? _C.working
                          : device.status === 'pending'     ? _C.pending
                          : device.status === 'not-working' ? _C.notWorking
                          : _C.wishlist;
        const statusLabel = _STATUS_LABELS[device.status] || device.status || '-';
        const title       = `#${devNum} — ${device.name || 'Unnamed'}`;

        // ── Build key/value rows ──────────────────────────────────────────────
        const rows = [];
        const add  = (k, v) => {
            const s = (v === null || v === undefined) ? '' : String(v).trim();
            if (s) rows.push([k, s]);
        };

        // ── Identity ──────────────────────────────────────────────────────────
        add('Status',          statusLabel);
        add('Brand',           device.brand);
        add('Model',           device.model);
        add('Type',            _fmtType(device.type));
        add('Serial Number',   device.serialNumber);

        const isWishlist = device.status === 'wishlist';
        const isPending  = device.status === 'pending';
        const isBattery  = device.power === 'battery';
        const isWired    = device.power && !isBattery;
        const battType   = (device.batteryType || '').toLowerCase().trim();

        // ── Location (hidden for wishlist / pending, same as form) ───────────
        if (!isWishlist && !isPending) {
            add('Installed Area',   area.name);
            add('Floor',            floor.name);
            if (device.controlledArea) {
                const ctrlArea = areaMap.get(device.controlledArea);
                add('Controlled Area', ctrlArea ? ctrlArea.name : device.controlledArea);
            }
            add('Installation Date', device.installationDate);
        }

        // ── Network ───────────────────────────────────────────────────────────
        add('Connectivity',    _fmtConnectivity(device.connectivity));
        add('IP Address',      device.ip);
        add('MAC Address',     device.mac);
        add('Network',         device.networkId);

        // Wi-Fi details (one row per field)
        if (device.wifiAccessPointId) {
            const ap   = devMap.get(String(device.wifiAccessPointId));
            const band = device.wifiBand ? `  (${device.wifiBand})` : '';
            rows.push(['Wi-Fi Access Point', `${ap ? ap.name : device.wifiAccessPointId}${band}`]);
        }
        if (device.wifiDownloadSpeed) add('Wi-Fi Download', device.wifiDownloadSpeed + ' Mbps');
        if (device.wifiUploadSpeed)   add('Wi-Fi Upload',   device.wifiUploadSpeed   + ' Mbps');

        // Zigbee / Z-Wave
        if (device.zigbeeParentId) {
            const zb = devMap.get(String(device.zigbeeParentId));
            rows.push(['Zigbee Parent', zb ? zb.name : device.zigbeeParentId]);
        }
        if (device.zwaveControllerId) {
            const zw = devMap.get(String(device.zwaveControllerId));
            rows.push(['Z-Wave Parent', zw ? zw.name : device.zwaveControllerId]);
        }

        // ── Storage ───────────────────────────────────────────────────────────
        if (device.storageSize !== undefined && device.storageSize !== null && String(device.storageSize).trim()) {
            const unit = device.storageUnit ? String(device.storageUnit).trim() : '';
            add('Storage', unit ? `${device.storageSize} ${unit}` : String(device.storageSize));
        }

        // ── Power ─────────────────────────────────────────────────────────────
        add('Power Source', _fmtPower(device.power));

        // Wired-only fields
        if (isWired) {
            add('UPS Protected',   device.upsProtected ? 'Yes' : 'No');
            if (device.idleConsumption != null) add('Idle Consumption', device.idleConsumption + ' W');
            if (device.meanConsumption != null) add('Mean Consumption', device.meanConsumption + ' W');
            if (device.maxConsumption  != null) add('Max Consumption',  device.maxConsumption  + ' W');
        }

        // ── Battery (only when power=battery, mirror form visibility) ─────────
        if (isBattery) {
            add('Battery Type', device.batteryType);
            // batteryCount hidden for 'internal' and 'usb' battery types
            if (battType && battType !== 'internal' && battType !== 'usb') {
                if (device.batteryCount != null) add('Battery Count', String(device.batteryCount));
            }
            // lastBatteryChange hidden for wishlist
            if (!isWishlist) add('Last Battery Change', device.lastBatteryChange);
            if (device.batteryDuration != null) add('Battery Duration', device.batteryDuration + ' months');
        }

        // ── Purchase & warranty ───────────────────────────────────────────────
        add('Purchase Date',      device.purchaseDate);
        add('Purchase Store',     device.purchaseStore);
        if (device.purchasePrice != null) {
            const currency = device.purchaseCurrency ? ' ' + device.purchaseCurrency : '';
            add('Purchase Price', device.purchasePrice + currency);
        }
        add('Warranty Expiration', device.warrantyExpiration);

        // ── Integrations & roles ──────────────────────────────────────────────
        add('Local Only', device.localOnly ? 'Yes' : 'No');
        const integrations = [];
        if (Array.isArray(device.haDeviceIds) && device.haDeviceIds.length > 0) integrations.push('Home Assistant');
        if (device.googleHome)         integrations.push('Google Home');
        if (device.alexa)              integrations.push('Amazon Alexa');
        if (device.appleHomeKit)       integrations.push('Apple HomeKit');
        if (device.samsungSmartThings) integrations.push('Samsung SmartThings');
        if (integrations.length) add('Integrations', integrations.join(', '));

        if (Array.isArray(device.haDeviceIds) && device.haDeviceIds.length > 0) {
            add('HA Device IDs', device.haDeviceIds.join(', '));
        }

        if (device.zigbeeController)   rows.push(['Zigbee Coordinator',   'Yes']);
        if (device.zigbeeRepeater)     rows.push(['Zigbee Router',         'Yes']);
        if (device.zwaveController)    rows.push(['Z-Wave Coordinator',    'Yes']);
        if (device.matterHub)          rows.push(['Matter Bridge',         'Yes']);
        if (device.threadBorderRouter) rows.push(['Thread Border Router',  'Yes']);

        // ── Labels ────────────────────────────────────────────────────────────
        if (Array.isArray(device.labels) && device.labels.length > 0) {
            const names = device.labels.map(id => (labelMap.get(id) || {}).name || null).filter(Boolean);
            if (names.length) add('Labels', names.join(', '));
        }

        // ── Links ─────────────────────────────────────────────────────────────
        if (Array.isArray(device.links)) {
            device.links.forEach(link => {
                if (link && link.url) rows.push([link.name || 'Link', link.url]);
            });
        }

        // ── Port connections — one row per port ───────────────────────────────
        if (Array.isArray(device.ports)) {
            device.ports
                .filter(p => p.connectedTo)
                .forEach(p => {
                    const target    = devMap.get(String(p.connectedTo));
                    const tName     = target ? target.name : String(p.connectedTo);
                    const portLabel = _PORT_LABELS[p.type] || p.type || 'Port';
                    const details   = [];
                    if (p.cableType) details.push(String(p.cableType).replace(/^cat/i, 'Cat'));
                    if (p.speed)     details.push(String(p.speed));
                    rows.push([portLabel, details.length ? `${tName}  (${details.join(', ')})` : tName]);
                });
        }

        // ── Notes ─────────────────────────────────────────────────────────────
        if (device.notes) add('Notes', device.notes);

        // ── Render autoTable ──────────────────────────────────────────────────
        doc.autoTable({
            theme:              'grid',
            startY:             _PDF_HEADER_H + 1,
            styles:             {
                fontSize: 8.3,
                cellPadding: 2.3,
                overflow: 'linebreak',
                lineColor: _C.tableGrid,
                lineWidth: 0.12,
                textColor: _C.textOnLight,
            },
            alternateRowStyles: { fillColor: _C.rowAlt },
            margin:             { top: _PDF_HEADER_H + 1, left: _PDF_MARGIN, right: _PDF_MARGIN, bottom: _PDF_BOTTOM_MARGIN },
            head: [[{
                content: title,
                colSpan: 2,
                styles: {
                    fillColor: statusColor,
                    textColor: [255, 255, 255],
                    fontStyle: 'bold',
                    fontSize:  10,
                    halign:    'left',
                },
            }]],
            body:               rows,
            columnStyles: {
                0: { cellWidth: 48, fontStyle: 'bold', textColor: _C.textStrong },
                1: { cellWidth: 'auto' },
            },
            didDrawPage: () => _drawPageHeader(doc, `Device Details — ${title}`),
        });
    });
}

// ─── Test Cases pages ──────────────────────────────────────────────────────────

function _pdfTestCasesPages(doc, data) {
    const testCases = (data.testCases || []).filter(tc => tc && tc.name);
    if (!testCases.length) {
        doc.addPage();
        _drawPageHeader(doc, 'Test Cases');
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(..._C.textOnLight);
        doc.text('No test cases defined.', _PDF_MARGIN, _PDF_HEADER_H + 10);
        return;
    }

    // Sort by category then name
    const sorted = [...testCases].sort((a, b) => {
        const ca = (a.category || 'General').localeCompare(b.category || 'General');
        return ca !== 0 ? ca : (a.name || '').localeCompare(b.name || '');
    });

    // Build rows with category header rows interspersed
    const body = [];
    let lastCategory = null;
    sorted.forEach(tc => {
        const cat = tc.category || 'General';
        if (cat !== lastCategory) {
            body.push([{
                content: cat,
                colSpan: 5,
                styles: {
                    fillColor: _C.tableHead,
                    textColor: _C.textLight,
                    fontStyle: 'bold',
                    fontSize: 8.5,
                },
            }]);
            lastCategory = cat;
        }
        const priority = (() => {
            const p = (tc.priority || 'medium').toLowerCase();
            if (p === 'high') return 'High';
            if (p === 'low')  return 'Low';
            return 'Medium';
        })();
        body.push([
            tc.name          || '',
            priority,
            tc.description   || '',
            tc.steps         || '',
            tc.expectedResult || '',
        ]);
    });

    doc.addPage();
    doc.autoTable({
        theme: 'grid',
        startY: _PDF_HEADER_H + 2,
        head: [[
            { content: 'Name',            styles: { halign: 'left' } },
            { content: 'Priority',        styles: { halign: 'center' } },
            { content: 'Description',     styles: { halign: 'left' } },
            { content: 'Steps',           styles: { halign: 'left' } },
            { content: 'Expected Result', styles: { halign: 'left' } },
        ]],
        body,
        styles: {
            fontSize:    7.5,
            cellPadding: 2,
            overflow:    'linebreak',
            lineColor:   _C.tableGrid,
            lineWidth:   0.12,
            textColor:   _C.textOnLight,
        },
        headStyles: {
            fillColor: _C.accent,
            textColor: [255, 255, 255],
            fontStyle: 'bold',
            fontSize:  8,
        },
        alternateRowStyles: { fillColor: _C.rowAlt },
        margin: { top: _PDF_HEADER_H + 2, left: _PDF_MARGIN, right: _PDF_MARGIN, bottom: _PDF_BOTTOM_MARGIN },
        columnStyles: {
            0: { cellWidth: 38, fontStyle: 'bold' },
            1: { cellWidth: 16, halign: 'center'  },
            2: { cellWidth: 'auto' },
            3: { cellWidth: 'auto' },
            4: { cellWidth: 'auto' },
        },
        didParseCell: (data) => {
            if (data.row.raw?.[0]?.colSpan === 5) return; // category row
            const priority = data.row.raw?.[1];
            if (data.column.index === 1 && data.section === 'body') {
                if (priority === 'High')   data.cell.styles.textColor = _C.notWorking;
                if (priority === 'Low')    data.cell.styles.textColor = _C.textOnLight;
                if (priority === 'Medium') data.cell.styles.textColor = _C.pending;
            }
        },
        didDrawPage: () => _drawPageHeader(doc, 'Test Cases'),
    });
}
